version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: strapi_postgres
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - strapi_net

  strapi:
    image: strapi-app:latest  
    container_name: strapi_app
    depends_on:
      - postgres
    environment:
      
      HOST: 0.0.0.0
      PORT: 1337
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: 'false'
    ports:
      - "1337:1337"   
    networks:
      - strapi_net
    volumes:
      - ./public/uploads:/app/public/uploads 

  nginx:
    image: nginx:alpine
    container_name: strapi_nginx
    depends_on:
      - strapi
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - strapi_net

volumes:
  db_data:

networks:
  strapi_net:
    driver: bridge
